export const GET_HEADER_VALUES = 'GET_HEADER_VALUES';
export const SET_HEADER_VALUES = 'SET_HEADER_VALUES';
export const UPDATE_ACCOUNT_TYPE = 'UPDATE_ACCOUNT_TYPE';

export const ON_APPLY_DATE_RANGE_ANALYTICS = 'ON_APPLY_DATE_RANGE_ANALYTICS';
export const UPDATE_ANALYTICS_RESPONSE = 'UPDATE_ANALYTICS_RESPONSE';
export const CLEAR_ANALYTICS_ARRAY = 'CLEAR_ANALYTICS_ARRAY';
export const LOG_ANALYTICS_ERROR = 'LOG_ANALYTICS_ERROR';
export const TOGGLE_ANALYTICS_ERROR_VIEW = 'TOGGLE_ANALYTICS_ERROR_VIEW';

export const SET_FORECAST_HISTORY_RESPONSE = 'SET_FORECAST_HISTORY_RESPONSE';
export const SET_FORECAST_FUTURE_RESPONSE = 'SET_FORECAST_FUTURE_RESPONSE';
export const UPDATE_FORECAST_ARRAY = 'UPDATE_FORECAST_ARRAY';
export const SET_FORECAST_DAYS_COUNT = 'SET_FORECAST_DAYS_COUNT';
export const CLEAR_FORECAST_ARRAY = 'CLEAR_FORECAST_ARRAY';

export const SET_ANOMALIES_RESPONSE = 'SET_ANOMALIES_RESPONSE';
export const CLEAR_ANOMALIES_RESPONSE = 'CLEAR_ANOMALIES_RESPONSE';

export const UPDATE_MOTH_DETAIL = 'UPDATE_MOTH_DETAIL';
export const LOAD_NEXT_MONTH = 'LOAD_NEXT_MONTH';
export const LOAD_PREVIOUS_MONTH = 'LOAD_PREVIOUS_MONTH';
export const SHOW_LOADING = 'SHOW_LOADING';

export const LOAD_AGENT_LIST = 'GET_AGENT_LIST';

export const UPDATE_GET_SHEET_NAME_MESSAGE = 'UPDATE_GET_SHEET_NAME_MESSAGE';
export const CLEAR_GET_SHEET_NAME_MESSAGE = 'CLEAR_GET_SHEET_NAME_MESSAGE';
export const TOGGLE_INTEGRATION_IMPORT_LOADER = 'TOGGLE_INTEGRATION_IMPORT_LOADER';

export const UPDATE_INTEGRATION_MAPPING_HEADERS = 'UPDATE_INTEGRATION_MAPPING_HEADERS';
export const UPDATE_INTEGRATION_MAPPING_FIXED_HEADERS = 'UPDATE_INTEGRATION_MAPPING_FIXED_HEADERS';
export const UPDATE_INTEGRATION_MAPPING_UPDATE_URL = 'UPDATE_INTEGRATION_MAPPING_UPDATE_URL';
export const TOGGLE_INTEGRATION_MAPPING_LOADER = 'TOGGLE_INTEGRATION_MAPPING_LOADER';
export const UPDATE_INTEGRATION_MAPPING_MAPPED_HEADERS = 'UPDATE_INTEGRATION_MAPPING_MAPPED_HEADERS';

export const UPDATE_INTEGRATION_STATUS = 'UPDATE_INTEGRATION_STATUS';

export const TOGGLE_ADMIN_VIEW = 'TOGGLE_ADMIN_VIEW';

// action type for clients
export const SET_CLIENTS_LIST = 'SET_CLIENTS_LIST';
