export const GET_HEADER_VALUES = 'GET_HEADER_VALUES';
export const SET_HEADER_VALUES = 'SET_HEADER_VALUES';
export const UPDATE_ACCOUNT_TYPE = 'UPDATE_ACCOUNT_TYPE';

export const ON_APPLY_DATE_RANGE_ANALYTICS = 'ON_APPLY_DATE_RANGE_ANALYTICS';
export const UPDATE_ANALYTICS_RESPONSE = 'UPDATE_ANALYTICS_RESPONSE';
export const CLEAR_ANALYTICS_ARRAY = 'CLEAR_ANALYTICS_ARRAY';
export const LOG_ANALYTICS_ERROR = 'LOG_ANALYTICS_ERROR';
export const TOGGLE_ANALYTICS_ERROR_VIEW = 'TOGGLE_ANALYTICS_ERROR_VIEW';

export const SET_FORECAST_HISTORY_RESPONSE = 'SET_FORECAST_HISTORY_RESPONSE';
export const SET_FORECAST_FUTURE_RESPONSE = 'SET_FORECAST_FUTURE_RESPONSE';
export const UPDATE_FORECAST_ARRAY = 'UPDATE_FORECAST_ARRAY';
export const SET_FORECAST_DAYS_COUNT = 'SET_FORECAST_DAYS_COUNT';
export const CLEAR_FORECAST_ARRAY = 'CLEAR_FORECAST_ARRAY';

export const SET_ANOMALIES_RESPONSE = 'SET_ANOMALIES_RESPONSE';
export const CLEAR_ANOMALIES_RESPONSE = 'CLEAR_ANOMALIES_RESPONSE';
